---
- include_vars: ../../common_vars.yml

- name: Copy init scripts to /etc/init.d
  become: yes
  copy:
    remote_src: true
    src: "{{ init_dir }}/{{ item }}"
    dest: "/etc/init.d"
    mode: 0755
  with_items:
    - snowplow_mini
    - snowplow_mini_control_plane_api
    - caddy

- name: Configure for inits for calling at boot time
  become: yes
  shell: "update-rc.d {{ item }} defaults"
  with_items:
    - snowplow_mini
    - snowplow_mini_control_plane_api
    - caddy

- name: Start Caddy
  become: yes
  shell: systemctl start caddy

- name: Start Control Plane
  become: yes
  shell: systemctl start snowplow_mini_control_plane_api

- cron:
    name: "Add cronjob to crop ES good index's docs older than a week"
    special_time: weekly
    job: /usr/bin/curl -s -X POST http://localhost:9200/good/_delete_by_query -H 'Content-Type:application/json' -d '{ "query" :{ "range" :{ "collector_tstamp" :{ "lt" :"now-1w/d" } } } }' > /dev/null 2>&1

- cron:
    name: "Add cronjob to crop ES bad index's docs older than a week"
    special_time: weekly
    job: /usr/bin/curl -s -X POST http://localhost:9200/bad/_delete_by_query -H 'Content-Type:application/json' -d '{ "query" :{ "range" :{ "failure_tstamp" :{ "lt" :"now-1w/d" } } } }' > /dev/null 2>&1
