---
- name: install basic packages
  become: yes
  apt:
    pkg: ['curl', 'unzip', 'resolvconf']
    state: latest
    update-cache: yes
    cache_valid_time: 86400
  tags: [packages]

- name: Add Google DNS nameserver
  lineinfile:
    dest="/etc/resolvconf/resolv.conf.d/head"
    line="nameserver 8.8.8.8"
  become: yes

- name: Restart resolveconf service
  become: yes
  service:
    name: resolvconf
    state: restarted
